# Generated by Django 4.1.5 on 2023-05-27 09:52

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netposts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('post_author', models.PositiveBigIntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_date_gmt', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', tinymce.models.HTMLField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_title', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_excerpt', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_status', models.CharField(max_length=20)),
                ('comment_status', models.CharField(max_length=20)),
                ('ping_status', models.CharField(max_length=20)),
                ('post_password', models.CharField(max_length=255)),
                ('post_name', models.CharField(db_collation='utf8mb4_persian_ci', max_length=200)),
                ('to_ping', models.TextField(blank=True, default='')),
                ('pinged', models.TextField(blank=True, default='')),
                ('post_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_modified_gmt', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content_filtered', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_parent', models.PositiveBigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('menu_order', models.IntegerField(blank=True, default='')),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(max_length=100)),
                ('comment_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'netposts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='antena',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('post_author', models.PositiveBigIntegerField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_date_gmt', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content', tinymce.models.HTMLField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_title', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_excerpt', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_status', models.CharField(max_length=20)),
                ('comment_status', models.CharField(max_length=20)),
                ('ping_status', models.CharField(max_length=20)),
                ('post_password', models.CharField(max_length=255)),
                ('post_name', models.CharField(db_collation='utf8mb4_persian_ci', max_length=200)),
                ('to_ping', models.TextField(blank=True, default='')),
                ('pinged', models.TextField(blank=True, default='')),
                ('post_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_modified_gmt', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_content_filtered', models.TextField(db_collation='utf8mb4_persian_ci')),
                ('post_parent', models.PositiveBigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('menu_order', models.IntegerField(blank=True, default='')),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(max_length=100)),
                ('comment_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(db_collation='utf8mb4_persian_ci', max_length=200)),
                ('subtitle', models.CharField(blank=True, db_collation='utf8mb4_persian_ci', default='', max_length=200)),
                ('article_slug', models.SlugField(blank=True, verbose_name='Article slug')),
                ('post_content', tinymce.models.HTMLField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('notes', tinymce.models.HTMLField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date modified')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, db_collation='utf8mb4_persian_ci', default='', max_length=100)),
                ('author_email', models.CharField(blank=True, default='', max_length=100)),
                ('author_url', models.CharField(blank=True, default='', max_length=200)),
                ('author_ip', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_gmt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_id', models.IntegerField(blank=True, default='')),
                ('approved', models.BooleanField(default=False, max_length=20)),
                ('agent', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.PositiveBigIntegerField()),
                ('post_date', models.DateTimeField()),
                ('post_date_gmt', models.DateTimeField()),
                ('post_content', tinymce.models.HTMLField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_title', models.TextField(blank=True, db_collation='utf8mb4_persian_ci', default='', max_length=255)),
                ('post_description', models.TextField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_status', models.CharField(max_length=20)),
                ('comment_status', models.CharField(max_length=20)),
                ('ping_status', models.CharField(max_length=20)),
                ('post_password', models.CharField(blank=True, default='', max_length=255)),
                ('post_name', models.CharField(db_collation='utf8mb4_persian_ci', max_length=200)),
                ('to_ping', models.TextField(blank=True, default='')),
                ('pinged', models.TextField(blank=True, default='')),
                ('post_modified', models.DateTimeField()),
                ('post_modified_gmt', models.DateTimeField()),
                ('post_keywords', models.TextField(blank=True, db_collation='utf8mb4_persian_ci', default='')),
                ('post_parent', models.PositiveBigIntegerField()),
                ('guid', models.CharField(max_length=255)),
                ('menu_order', models.IntegerField()),
                ('post_type', models.CharField(max_length=20)),
                ('post_mime_type', models.CharField(blank=True, default='c', max_length=100)),
                ('comment_count', models.BigIntegerField()),
            ],
        ),
    ]
